# configs/config.yaml

app:
  name: Empathetic ACE Chatbot
  version: 1.0.0
  description: A chatbot that evaluates ACE responses and chats empathetically

server:
  host: 0.0.0.0
  port: 8000

model:
  name: facebook/blenderbot-400M-distill
  temperature: 0.7
  max_tokens: 200

questionnaire:
  path: questionnaire/ace_questions.json

storage:
  type: local  # or "s3" or "postgres"
  db_uri: postgresql://user:password@localhost/dbname
  s3_bucket: ace-chatbot-bucket
  save_chat_history: true

auth:
  hf_token: ${HF_TOKEN}  #still working on other models